In [1]:
import numpy

In [2]:
import numpy as np

# Numpy Array

In [3]:
b = np.array([1, 2, 3, 4])

In [4]:
b

array([1, 2, 3, 4])

In [5]:
my_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [6]:
my_arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
my_arr[1, 2]

7

In [8]:
my_arr[1][2]

7

In [9]:
my_arr.ndim

2

In [10]:
my_arr.shape

(2, 4)

In [11]:
my_arr.size

8

In [12]:
type(my_arr)

numpy.ndarray

## Creating Numpy Arrays

In [13]:
a = np.ones((3, 2))

In [14]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
c = np.random.random((3, 3))

In [17]:
c

array([[0.04458459, 0.44138191, 0.97944106],
       [0.91856642, 0.60386522, 0.37066318],
       [0.54942844, 0.2839366 , 0.10232685]])

In [18]:
d = np.full((2,2), 12)

In [19]:
d

array([[12, 12],
       [12, 12]])

In [20]:
e = np.empty([2, 2])

In [21]:
e

array([[4.64036684e-310, 0.00000000e+000],
       [6.94537181e-310, 0.00000000e+000]])

In [22]:
f = np.eye(3)

In [23]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
g = np.identity(3)

In [25]:
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
h = g.copy()

In [27]:
h

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Creating a sequence

In [29]:
i = np.arange(0, 10, 2)
i

array([0, 2, 4, 6, 8])

In [30]:
j = np.linspace(0, 10, 6)

In [31]:
j

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [32]:
k = np.linspace(0, 10, 5)
k

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Changing Array Shape & Size

In [33]:
l = np.arange(10)

In [35]:
l.shape

(10,)

In [36]:
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
l.resize(2, 5)

In [38]:
l.shape

(2, 5)

In [39]:
l

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
m.shape

(2, 3)

In [43]:
m.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
m.ravel()

array([1, 2, 3, 4, 5, 6])

In [46]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
m.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
n = np.eye(5)

In [49]:
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
n.transpose()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Array Slicing

In [51]:
p = np.arange(8)

In [52]:
p

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
q = p[0:4]
q

array([0, 1, 2, 3])

In [54]:
p[6: ]

array([6, 7])

In [55]:
p[ :5]

array([0, 1, 2, 3, 4])

In [56]:
p[1] = 50

In [57]:
p

array([ 0, 50,  2,  3,  4,  5,  6,  7])

In [58]:
r = np.array([[10, 11, 12, 13], [20, 22, 23, 25]])
r

array([[10, 11, 12, 13],
       [20, 22, 23, 25]])

In [59]:
r[0:1, 1]

array([11])

In [60]:
r[0][1]

11

## Numpy Arithmetics

In [61]:
s = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
t = np.array([[9, 10, 11, 12], [13, 14, 15, 16]])

In [63]:
np.add(s, t)

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [64]:
np.remainder(t, s)

array([[0, 0, 2, 0],
       [3, 2, 1, 0]])

In [65]:
s**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [66]:
t - s

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [67]:
s < 5

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [68]:
s + t

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [69]:
s * t

array([[  9,  20,  33,  48],
       [ 65,  84, 105, 128]])

In [71]:
np.exp(s)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [72]:
np.sqrt(s)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712]])

In [74]:
u = np.array([[2.567, 2.764, 3.3728], [4.7927, 2.80742, 6.796387]])

In [75]:
u

array([[2.567   , 2.764   , 3.3728  ],
       [4.7927  , 2.80742 , 6.796387]])

In [76]:
np.around(u, 2)

array([[2.57, 2.76, 3.37],
       [4.79, 2.81, 6.8 ]])

In [77]:
np.trunc(u)

array([[2., 2., 3.],
       [4., 2., 6.]])

In [78]:
np.floor(u)

array([[2., 2., 3.],
       [4., 2., 6.]])

In [79]:
np.ceil(u)

array([[3., 3., 4.],
       [5., 3., 7.]])

In [80]:
np.log(u)

array([[0.9427379 , 1.01667891, 1.21574326],
       [1.56709393, 1.03226591, 1.91639115]])

## Array Functions

In [81]:
u

array([[2.567   , 2.764   , 3.3728  ],
       [4.7927  , 2.80742 , 6.796387]])

In [82]:
t

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [83]:
s

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
s.sum(axis = 0)

array([ 6,  8, 10, 12])

In [85]:
np.min(s)

1

In [86]:
np.max(s)

8

In [87]:
np.cumsum(s)

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [88]:
np.corrcoef(s)

array([[1., 1.],
       [1., 1.]])

In [89]:
t.std()

2.29128784747792

## Numpy BroadCasting

In [90]:
two_d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
one_d = np.array([[10]])
three_d = np.ones((3, 2))

In [91]:
np.add(two_d, one_d)

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [92]:
np.add(one_d, three_d)

array([[11., 11.],
       [11., 11.],
       [11., 11.]])

In [93]:
one_d

array([[10]])

In [94]:
one_d.shape

(1, 1)

In [95]:
np.add(two_d, three_d)

ValueError: operands could not be broadcast together with shapes (2,4) (3,2) 